# Generated by Django 5.2 on 2025-04-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.TextField()),
                ("score", models.TextField()),
                ("turn", models.TextField()),
                ("board_state", models.TextField()),
                ("game_state", models.TextField()),
                ("timer", models.TextField()),
                ("move", models.TextField()),
            ],
        ),
    ]
