name: Black
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}      
      - uses: psf/black@stable
        with:
          options: "--quiet"
          src: "./backend"
          version: "~= 22.0"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: black linter auto changes
          branch: ${{ github.head_ref }}
