name: linters
on:
  push:
    branches:
      - main
      - linter_tests

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run format

      - uses: psf/black@stable
        with:
          options: "--quiet"
          src: "./backend"
          version: "~= 22.0"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: linters auto changes
          branch: ${{ github.head_ref }}
